name: Update articles
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-latest-articles:
    name: Update articles section of README.md
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          commit_message: 'Update README.md with the latest articles'
          committer_email: 'hozlucas28@gmail.com'
          committer_username: 'Update articles [GitHub Action]'
          feed_list: 'https://medium.com/feed/@hozlucas28'
          max_post_count: 3
          template: '$newline    <li><a href="$url">$title</a></li>'
